apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demopod
  name: demopod
spec:
  containers:
  - image: nginx
    name: demopod
    resources: {}
    volumeMounts:
      - mountPath: /data
        name: first-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: first-volume
      hostPath:
        path: /home/siddharth/mydata
        type: DirectoryOrCreate
status: {}