# kubectl create priorityclass high-priority --value=1000 --description="high priority"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-priority-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: high-priority
  template:
    metadata:
      labels:
        app: high-priority
    spec:
      priorityClassName: high-priority
      containers:
      - name: busybox
        image: nginx
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "100Mi"
            cpu: "100m"