apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-echo
  name: busybox-echo
spec:
  containers:
    - image: busybox
      name: busybox-echo
      command: ["ping", "-c", "60", "google.com"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
