apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test
spec: {}
status: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: test
type: Opaque
data:
  DB_USERNAME: YWRtaW4K
  DB_PASSWORD: c3VwZXJzZWNyZXQK

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample
  name: sample
  namespace: test
spec:
  containers:
  - image: nginx:latest
    name: sample
    resources: {}
    env:
    - name: APP_DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_USERNAME
    - name: APP_DB_PASS
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWORD
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---