apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-v1
  name: app-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-v1
        srv: cannary-default
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dep: app-v2
  name: app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      dep: app-v2
  strategy: {}
  template:
    metadata:
      labels:
        dep: app-v2
        srv: cannary-default
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    srv: cannary-default
  type: LoadBalancer
status:
  loadBalancer: {}