apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-pod
  name: security-pod
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 2002
  containers:
  - image: busybox:latest
    name: security-pod
    resources: {}
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
