apiVersion: v1
kind: Namespace
metadata:
  name: limits
spec: {}
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cpu-mem-limits
  name: cpu-mem-limits
  namespace: limits
spec:
  restartPolicy: Never
  containers:
  - image: busybox:latest
    name: cpu-mem-limits
    resources:
      limits:
        memory: "256Mi"
        cpu: "80m"
      requests:
        memory: "50Mi"
        cpu: "20m"
    args: ["sh", "-c", "sleep 100s"]
  dnsPolicy: ClusterFirst
status: {}