apiVersion: v1
kind: Pod
metadata:
  name: capabilities-pod-1
spec:
 containers:
 - name: demo
   image: busybox
   command: ["sleep","36000"]
   securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]