apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
 containers:
 - name: demo-container
   image: busybox:latest
   command: ["sleep", "36000"]
   
   volumeMounts:
    - name: host-root
      mountPath: /host
 volumes:
  - name: host-root
    hostPath:
      path: /  