apiVersion: v1
kind: Pod
metadata:
  name: capabilities-pod-2
spec:
 containers:
 - name: demo-2
   image: busybox
   command: ["sleep","36000"]
   securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
        drop:
        - ALL